### PR TITLE
Introducing Pycryptodome

### PR DESCRIPTION
**Pull request by alexmgr**
- Removed pycrypto in favour of pycryptodome. Same interface
- Added AES GCM mode
- Added and modified dependent unit-tests

### CODE REVIEW

**Comment by alexmgr** [comment]
Still need to populate the `TLSSecurityParameters.crypto_params` table with the remaining ciphers. Also need to account for cipher_suite specific PRFs.

**Comment by alexmgr** [comment]
Close to all good. Requires adding all available GCM ciphers to `TLSSecurityParameters.crypto_params` table.

Last thing would be to mark `pycrypto` as a conflict with `pycryptodome`. Unfortunalty not sure how to do this through `setuptools`. Can't find any `setup()` attribute in the docs to do that.

**Comment by alexmgr** [comment]
All set here. We should be ready to go for `TLS 1.3` implementation when time allows.

@tintinweb: could you give this a quick test when time allows. Already done due diligence, but who knows ;)

**Comment by tintinweb** [comment]
will do! 👍

**Comment by tintinweb** [comment]
* integration testsuite raised one issue with the `RSA.pubkey.size()` -> `RSA.pubkey.size_in_bits()` 👍 
* changed version to v1.3.0 considering this is a major change or do we want to stay at v1.2.4? what do you think?

**Comment by alexmgr** [comment]
Hi Tin,

Thanks for testing it out, and good catch regarding `size()` change. Looks like your integration branch is working well.

Agreed on versioning bump. Should probably warn that anything relying on `TLSSessionCtx` will break with this new version. Otherwise external interface is identical.

**Comment by tintinweb** [comment]
If you feel like you can add any information on noteworthy changes to the release draft in releases/tags or send it to me and I ll add it :+1

**Comment by alexmgr** [comment]
@tintinweb Will put something together

One thing that I think might break is that we can't have `pycrypto` and `pycryptodome` in the same `site-package`. I couldn't find a `setuptools` directive to mark the conflict in `setup()`. Might want to address that before we release. I'm not sure how to do that right now, but I'll try and look into it.

**Comment by alexmgr** [comment]
Hi @tintinweb,

Noteworthy release points I can remember:
* Introduction of Asymmetrical, Key Exchange and Symmetrical keystores
* Support for TLS 1.2 AEAD ciphers (GCM and CCM)
* Support for TLS 1.2 cipher defined KDF
* Removal of `pycrypto` dependency, replaced by `pycryptodome`
* Refactor of `TLSSessionCtx`. External interface preserved, but scripts depending on `TLSSessionCtx` variables will need to be adjusted
* Support for session resumption

**Comment by tintinweb** [comment]
👍 thanks for updating the v1.3.0 draft!

Btw. we *can* run `pycryptodome` and `pycrypto` in [parallel](http://pycryptodome.readthedocs.io/en/latest/src/introduction.html) by using `pycryptodomex` package instead of `pycryptodome`.  It will then have a `Cryptodome` namespace instead of `Crypto`. That should solve the namespace conflict.

**Pull request merged**
