### PR TITLE
Added automatic decryption of protocols

### PR DESCRIPTION
**Pull request by alexmgr**
Was lazy with unittests, will add tomorrow, getting late here ;). But the general idea is here.
Might add a some logic to present the decrypted bytes, mac and padding separate also.

- Fixed bug in crypto container where wrong counter was incremented
- Added post_dissect() to TLS() to handle automatic decryption of
traffic
- Added example of a full TLS connection
- Removed dead code and unittests

### CODE REVIEW

**Comment by alexmgr** [comment]
Initial approach for decryption. Let me know your thoughts. Looks like this (with raw mac and padding):
```
###[ SSL/TLS ]###
  \records   \
   |###[ TLS Record ]###
   |  content_type= application_data
   |  version   = TLS_1_0
   |  length    = 0x20
   |###[ TLS Plaintext ]###
   |     data      = '^Vvm\xf6o\x1a\xe2\xb3\xd9}]d!0\x08\xe1\xea\xa0\xb4\x0b\x0b\x0b\x0b\x0b\x0b\x0b\x0b\x0b\x0b\x0b\x0b'
   |###[ TLS Record ]###
   |  content_type= application_data
   |  version   = TLS_1_0
   |  length    = 0x7e0
   |###[ TLS Plaintext ]###
   |     data      = 'HTTP/1.0 200 ok\r\nContent-type: text/html\r\n\r\n<HTML><BODY BGCOLOR="#ffffff">\n<pre>\n\ns_server -accept 8443 -www -debug -msg -key keys/key.pem -cert keys/cert.pem -tls1 -no_ssl3 \nCiphers supported in s_server binary\nTLSv1/SSLv3:DHE-RSA-AES256-SHA       TLSv1/SSLv3:DHE-DSS-AES256-SHA       \nTLSv1/SSLv3:AES256-SHA               TLSv1/SSLv3:EDH-RSA-DES-CBC3-SHA     \nTLSv1/SSLv3:EDH-DSS-DES-CBC3-SHA     TLSv1/SSLv3:DES-CBC3-SHA             \nTLSv1/SSLv3:DHE-RSA-AES128-SHA       TLSv1/SSLv3:DHE-DSS-AES128-SHA       \nTLSv1/SSLv3:AES128-SHA               TLSv1/SSLv3:DHE-RSA-SEED-SHA         \nTLSv1/SSLv3:DHE-DSS-SEED-SHA         TLSv1/SSLv3:SEED-SHA                 \nTLSv1/SSLv3:RC4-SHA                  TLSv1/SSLv3:RC4-MD5                  \nTLSv1/SSLv3:EDH-RSA-DES-CBC-SHA      TLSv1/SSLv3:EDH-DSS-DES-CBC-SHA      \nTLSv1/SSLv3:DES-CBC-SHA              TLSv1/SSLv3:EXP-EDH-RSA-DES-CBC-SHA  \nTLSv1/SSLv3:EXP-EDH-DSS-DES-CBC-SHA  TLSv1/SSLv3:EXP-DES-CBC-SHA          \nTLSv1/SSLv3:EXP-RC2-CBC-MD5          TLSv1/SSLv3:EXP-RC4-MD5              \n---\nCiphers common between both SSL end points:\nAES128-SHA\n---\nNew, TLSv1/SSLv3, Cipher is AES128-SHA\nSSL-Session:\n    Protocol  : TLSv1\n    Cipher    : AES128-SHA\n    Session-ID: E0B999BE6B631543518EEC1A6FE210718D3365FED87C68D687442371B01E71D1\n    Session-ID-ctx: 01000000\n    Master-Key: 8EEBE3B70904F32CDC6BFD2F459BB92DA91EAB54A803C99B0D6750C60714896A225F0CA4BFD36A468501625DF91DD510\n    Key-Arg   : None\n    Start Time: 1432708754\n    Timeout   : 7200 (sec)\n    Verify return code: 0 (ok)\n---\n   1 items in the session cache\n   0 client connects (SSL_connect())\n   0 client renegotiates (SSL_connect())\n   0 client connects that finished\n   1 server accepts (SSL_accept())\n   0 server renegotiates (SSL_accept())\n   1 server accepts that finished\n   0 session cache hits\n   0 session cache misses\n   0 session cache timeouts\n   0 callback cache hits\n   0 cache full overflows (128 allowed)\n---\nno client certificate available\n</BODY></HTML>\r\n\r\n\xf27\x12!^{\xd9\x9c\x8d:\xed~"\xb2\xf9\x0c\x97I\x1f\'\n\n\n\n\n\n\n\n\n\n\n'

```

**Comment by alexmgr** [comment]
Not easy to test, because the crypto material needs to be static. Added a bunch of unittests with fixed parameters.

**Comment by tintinweb** [comment]
//only have limited connectivity+mobile access until Im back home early next week. Sry for my brief response.

Nice stuff!


Ad. Testing: you may use the rsa-aes pcap from tests/files. It's static crypto. Privkey file should be in the same folder.

Ad. Mac: check out readme.md theres an example of what I had in place earlier. I think it would be nice adding a dedicated mac layer chained to the plaintext layer when applicable.

**Comment by alexmgr** [comment]
Already added UT, that was an old comment ;)

I'll look into options to parse mac and padding. I think your case was simpler cause you had a hard-coded MAC length, here the layer will have to know the length through TLSSessionCtx. I'd also rather have them as another field, then an additional layer. Will play around and see what works out best.

**Comment by alexmgr** [comment]
Added parsing of plaintext layers. Output is now similar to this in CBC mode:
```
###[ SSL/TLS ]###
  \records   \
   |###[ TLS Record ]###
   |  content_type= change_cipher_spec
   |  version   = TLS_1_0
   |  length    = 0x1
   |###[ TLS ChangeCipherSpec ]###
   |     message   = '\x01'
   |###[ TLS Record ]###
   |  content_type= handshake
   |  version   = TLS_1_0
   |  length    = 0x30
   |###[ TLS Plaintext ]###
   |     data      = '\x14\x00\x00\x0c\x17\nm\xc6\xe8\x07[\xfcI\xed\xb4\x97'
   |     mac       = '4\xe1!\xe7\x02\xa6\x14Y\xf2o\x91\xac\x0cc\xd8X\xb8m\xff\x97'
   |     padding   = '\x0b\x0b\x0b\x0b\x0b\x0b\x0b\x0b\x0b\x0b'
   |     padding_len= 0xb

###[ SSL/TLS ]###
  \records   \
   |###[ TLS Record ]###
   |  content_type= application_data
   |  version   = TLS_1_0
   |  length    = 0x20
   |###[ TLS Plaintext ]###
   |     data      = ''
   |     mac       = '\x18\xd3\xe6\xc3\xae\xe4\xf1@t\x9b\xd8{&\x01\x9a\x9a\x8e\xf4a+'
   |     padding   = '\x0b\x0b\x0b\x0b\x0b\x0b\x0b\x0b\x0b\x0b'
   |     padding_len= 0xb
   |###[ TLS Record ]###
   |  content_type= application_data
   |  version   = TLS_1_0
   |  length    = 0x7e0
   |###[ TLS Plaintext ]###
   |     data      = 'HTTP/1.0 200 ok\r\nContent-type: text/html\r\n\r\n<HTML><BODY BGCOLOR="#ffffff">\n<pre>\n\ns_server -accept 8443 -www -debug -msg -key keys/key.pem -cert keys/cert.pem -tls1 -no_ssl3 \nCiphers supported in s_server binary\nTLSv1/SSLv3:DHE-RSA-AES256-SHA       TLSv1/SSLv3:DHE-DSS-AES256-SHA       \nTLSv1/SSLv3:AES256-SHA               TLSv1/SSLv3:EDH-RSA-DES-CBC3-SHA     \nTLSv1/SSLv3:EDH-DSS-DES-CBC3-SHA     TLSv1/SSLv3:DES-CBC3-SHA             \nTLSv1/SSLv3:DHE-RSA-AES128-SHA       TLSv1/SSLv3:DHE-DSS-AES128-SHA       \nTLSv1/SSLv3:AES128-SHA               TLSv1/SSLv3:DHE-RSA-SEED-SHA         \nTLSv1/SSLv3:DHE-DSS-SEED-SHA         TLSv1/SSLv3:SEED-SHA                 \nTLSv1/SSLv3:RC4-SHA                  TLSv1/SSLv3:RC4-MD5                  \nTLSv1/SSLv3:EDH-RSA-DES-CBC-SHA      TLSv1/SSLv3:EDH-DSS-DES-CBC-SHA      \nTLSv1/SSLv3:DES-CBC-SHA              TLSv1/SSLv3:EXP-EDH-RSA-DES-CBC-SHA  \nTLSv1/SSLv3:EXP-EDH-DSS-DES-CBC-SHA  TLSv1/SSLv3:EXP-DES-CBC-SHA          \nTLSv1/SSLv3:EXP-RC2-CBC-MD5          TLSv1/SSLv3:EXP-RC4-MD5              \n---\nCiphers common between both SSL end points:\nAES128-SHA\n---\nNew, TLSv1/SSLv3, Cipher is AES128-SHA\nSSL-Session:\n    Protocol  : TLSv1\n    Cipher    : AES128-SHA\n    Session-ID: E4AFB6AED45A8917BCA47FBA9BFA7446B00C1C18F592C36A846BCA141407856D\n    Session-ID-ctx: 01000000\n    Master-Key: D429372089DD0862DAD8B83A62D5261A7F7F6EF4E2DA27C65C617648169505152477F8CCA81EEB96B07B50398F899536\n    Key-Arg   : None\n    Start Time: 1433111790\n    Timeout   : 7200 (sec)\n    Verify return code: 0 (ok)\n---\n   1 items in the session cache\n   0 client connects (SSL_connect())\n   0 client renegotiates (SSL_connect())\n   0 client connects that finished\n   1 server accepts (SSL_accept())\n   0 server renegotiates (SSL_accept())\n   1 server accepts that finished\n   0 session cache hits\n   0 session cache misses\n   0 session cache timeouts\n   0 callback cache hits\n   0 cache full overflows (128 allowed)\n---\nno client certificate available\n</BODY></HTML>\r\n\r\n'
   |     mac       = '\xa3\xa5(\xbf\x86\x91+=\x86\x1f\xb0\xb8\x1d0\xbb\xbb\x85@\x87\xf6'
   |     padding   = '\n\n\n\n\n\n\n\n\n'
   |     padding_len= 0xa
```

**Comment by tintinweb** [comment]
pretty cool stuff! even better than what I had in my mind :) great work, thanks! :+1:

**Pull request merged**
