### PR TITLE
Modified project layout to conform to setuptools

### PR DESCRIPTION
**Pull request by alexmgr**
Cleaned up the project layout to conform to setuptools. Integrated unittests with setuptools.

- No code change
- Modified test imports
- Included nosetests to run setuptools tests from setup.py

### CODE REVIEW

**Comment by alexmgr** [comment]
We should merge this early. Should make our life way easier,

**Comment by tintinweb** [comment]
excellent, we should merge branch pypi_packaging into this branch (contains setup.py fixups for pypi) and do the big file/rename merge once the other PRs are in. what do you think?

**Comment by alexmgr** [comment]
Agreed, that was also my plan. Since the Pypi branch was small, I was planning on just porting the changes into this, and not bothering with a merge.
Let's merge the certificate parsing stuff (after rebase), then this. I have actually got a scapy style solution to the dissection problem, where scapy indeed does most of the work. I'll rebase on top of this merge and then I'll create a PR for it.

**Comment by tintinweb** [comment]
sry, had do rebase and fix my conflicting merge to master 8e65b57805fe68ceaf08f2fc2ef0d1e4877d88ab
also changed the package path in setup.py to reflect the new folder structure.

**Pull request merged**
