### PR TITLE
Added a TLSSocket proxy implementation

### PR DESCRIPTION
**Pull request by alexmgr**
- TLSSocket proxies the socket class. It serializes and inserts
packets into TLSSessionCtx
- Fixed a bug in CryptoContainer where padding was added for stream
ciphers
- Modified TLS connection example to use TLSSocket
- TLSSocket should make all this usable within the scapy CLI, which
is a nice win

### CODE REVIEW

**Comment by alexmgr** [comment]
Forced build to fail with NotImplementedErro, until I properly add unittest coverage. Requires mocking socket.

**Comment by alexmgr** [comment]
Would you mind if we push this in without unittests? They would be such a pain to write and would require mock module.
I think the risk is pretty low, since it doesn't perform any logic. Let me know what you think

**Comment by alexmgr** [comment]
Needs rebasing. Will do tomorrow.

**Comment by tintinweb** [comment]
:+1: finally we got rid of these crappy sendrcv methods ;)

**Pull request merged**
