### PR TITLE
Full TLS 1.2 support

### PR DESCRIPTION
**Pull request by alexmgr**
- Made the required PRF changes
- Modified the verify_data generation
- Added unitests for PRFs

Gave it a quick spin, and I can speak TLS 1.2 to both openssl and Java, as well as a bunch of sites.

### CODE REVIEW

**Comment by alexmgr** [comment]
Probably needs double checking and a test spin, but looking good

**Comment by tintinweb** [comment]
I'll have this tested an merged in the next days. great work!

**Comment by tintinweb** [comment]
works fine with(DHE_RSA_WITH_AES_128_CBC_SHA, RSA_WITH_AES_128_CBC_SHA)x(tls1.0, tls1.1, tls1.2)
* openssl s_server 
* apache2 / openssl
* polarssl
* Microsoft-IIS/8.5 (schannel)
* 50 topsites (RSA_WITH_AES_128_CBC_SHA)

**Comment by alexmgr** [comment]
Thanks for testing!

**Pull request merged**
